// RootLayout.js

import React from "react";
import { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { getPages } from "@/sanity/sanity-utils";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bridging The Canyon",
  description: "Generated by Next & Sanity.io",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pages = await getPages();

  return (
    <html lang="en">

      <body className="mx-auto sm:max-w-[99%] sm:px-5 md:max-w-[95%] md:px-5 lg:max-w-[67%] bg-center">

        <header className="flex flex-col items-center justify-between pt-10 lg:flex-row">
          <Link href="/" className="logo text-center bg-gradient-to-r from-gray-400 via-teal-300 to-indigo-600
            bg-clip-text text-transparent text-2xl font-bold lg:mr-8 mb-4 lg:mb-0">
            Bridging The Canyon
          </Link>

          <nav className="flex lg:flex items-center gap-5 text-md text-gray-600 sm:px-5">
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="bg-gradient-to-r from-gray-400 via-teal-300 to-indigo-600
              bg-clip-text text-transparent hover:underline">
                {page.title}
              </Link>
            ))}
          </nav>
        </header>

        <main className="py-8 px-1">{children}</main>

        
      </body>
    </html>
  );
}
